# Generated by Django 4.2 on 2023-05-31 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='place',
            new_name='Place',
        ),
    ]
